/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dqlsv;

/**
 *
 * @author hien
 */
public class fr_main extends javax.swing.JFrame {

    /**
     * Creates new form fr_main
     */
    public fr_main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnKhoa = new javax.swing.JMenuItem();
        mnLop = new javax.swing.JMenuItem();
        mnMonHoc = new javax.swing.JMenuItem();
        mnQL = new javax.swing.JMenu();
        mnQLSV = new javax.swing.JMenuItem();
        mnDiem = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        mnAbout = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dqlsv/welcome.png"))); // NOI18N

        jMenu1.setText("Hệ Thống");

        jMenuItem1.setText("--------------");
        jMenuItem1.setEnabled(false);
        jMenu1.add(jMenuItem1);

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        jMenu1.add(mnExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Danh Mục");

        mnKhoa.setText("Khoa");
        mnKhoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnKhoaActionPerformed(evt);
            }
        });
        jMenu2.add(mnKhoa);

        mnLop.setText("Lớp");
        mnLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLopActionPerformed(evt);
            }
        });
        jMenu2.add(mnLop);

        mnMonHoc.setText("Môn Học");
        mnMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMonHocActionPerformed(evt);
            }
        });
        jMenu2.add(mnMonHoc);

        jMenuBar1.add(jMenu2);

        mnQL.setText("Quản Lý");
        mnQL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnQLActionPerformed(evt);
            }
        });

        mnQLSV.setText("Sinh Viên");
        mnQLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnQLSVActionPerformed(evt);
            }
        });
        mnQL.add(mnQLSV);

        mnDiem.setText("Điểm");
        mnDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDiemActionPerformed(evt);
            }
        });
        mnQL.add(mnDiem);

        jMenuBar1.add(mnQL);

        jMenu6.setText("Trợ giúp");

        jMenuItem5.setText("===============");
        jMenuItem5.setEnabled(false);
        jMenu6.add(jMenuItem5);

        mnAbout.setText("About");
        mnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutActionPerformed(evt);
            }
        });
        jMenu6.add(mnAbout);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnQLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnQLSVActionPerformed
        fr_QLSV qlsv=new fr_QLSV();
        qlsv.setVisible(true);
    }//GEN-LAST:event_mnQLSVActionPerformed

    private void mnLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLopActionPerformed
        fr_Lop lop = new fr_Lop();
        lop.setVisible(true);
    }//GEN-LAST:event_mnLopActionPerformed

    private void mnQLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnQLActionPerformed
        
    }//GEN-LAST:event_mnQLActionPerformed

    private void mnDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDiemActionPerformed
        fr_QLDIEM qldiem=new fr_QLDIEM();
        qldiem.setVisible(true);
    }//GEN-LAST:event_mnDiemActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutActionPerformed
        fr_about about = new fr_about();
        about.setVisible(true);
    }//GEN-LAST:event_mnAboutActionPerformed

    private void mnKhoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnKhoaActionPerformed
        fr_Khoa khoa = new fr_Khoa();
        khoa.setVisible(true);
    }//GEN-LAST:event_mnKhoaActionPerformed

    private void mnMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMonHocActionPerformed
        fr_MonHoc monhoc = new fr_MonHoc();
        monhoc.setVisible(true);
    }//GEN-LAST:event_mnMonHocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fr_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fr_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fr_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fr_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fr_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem mnAbout;
    private javax.swing.JMenuItem mnDiem;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenuItem mnKhoa;
    private javax.swing.JMenuItem mnLop;
    private javax.swing.JMenuItem mnMonHoc;
    private javax.swing.JMenu mnQL;
    private javax.swing.JMenuItem mnQLSV;
    // End of variables declaration//GEN-END:variables
}
